<?php
class struct{
//定义左侧按钮
/*用户权限字符串
控制器名，  控制器名_方法名  ,支持 星号 ，参见 AdminModule.php 
*/ 
	
	//允许全体管理员使用的方法	
	public static $public_user_auth=array(
			'site_*',
			'post_verifyCode',
			'frame_*',
			'infoCategory_showCategoryLeftmenu',
			'infoCategory_getCateTotalInfo',
			'info_cutImage',
	
	);
    public static $menu_left=array(
    array('title'=>'内容中心','auth_tag'=>'content_center','url'=>'/index.php?m=admin&c=left?auth_tag=content_center',
        'smenu'=>array(
            array(
                'title'=>'栏目管理',
                'url'=>'/index.php/admin/infoCategory/index/',
                'auth_tag'=>'infoCategory',
                'auth_func'=>array(
                    array('name'=>'查看分类','auth_tag'=>'infoCategory_index'),
                    array('name'=>'编辑分类','auth_tag'=>'infoCategory_update*'),
                    array('name'=>'删除分类','auth_tag'=>'infoCategory_delete'),
                ),
            ),
        		
			array(
                'title'=>'内容管理',
                'url'=>'/index.php/admin/infoFrame/index/',
                'auth_tag'=>'info',
                'auth_func'=>array(
                    array('name'=>'查看内容列表','auth_tag'=>'info_index'),
                    array('name'=>'编辑内容','auth_tag'=>'info_update*'),
					array('name'=>'删除内容','auth_tag'=>'info_delete'),
					array('name'=>'审核内容','auth_tag'=>'info_audit'),
                	array('name'=>'加入专题','auth_tag'=>'info_setSpecial'),
                	array('name'=>'加入推荐','auth_tag'=>'info_setRecommend'),
                	array('name'=>'转移分类','auth_tag'=>'info_setInfoCate'),
                	
                ),
            ),
            array(
            		'title'=>'分类管理',
            		'url'=>'/index.php/admin/linkageType/index/',
            		'auth_tag'=>'linkage',
            		'auth_func'=>array(
            				array('name'=>'查看联动分类','auth_tag'=>'linkage_index*'),
            				array('name'=>'编辑联动分类','auth_tag'=>'linkage_update*'),
            				array('name'=>'删除联动分类','auth_tag'=>'linkage_delele*'),
            		),
            ),
            array(
            		'title'=>'采集管理',
            		'url'=>'/index.php/admin/collector/index/',
            		'auth_tag'=>'collector',
            		'auth_func'=>array(
            			
            		),
            		'hide'=>1,
            ),
			array(
                'title'=>'内容评论',
                'url'=>'/index.php/admin/comment/index/',
                'auth_tag'=>'comment',
                'auth_func'=>array(
				    array('name'=>'查看评论列表','auth_tag'=>'comment_show'),
                    array('name'=>'审核评论','auth_tag'=>'comment_edit'),
					array('name'=>'删除评论','auth_tag'=>'comment_del'),
                ),
					'hide'=>1,
            ),
			array(
                'title'=>'专题管理',
                'url'=>'/index.php/admin/special/index/',
                'auth_tag'=>'special',
                'auth_func'=>array(
				    array('name'=>'查看专题','auth_tag'=>'special_index'),
                    array('name'=>'编辑专题','auth_tag'=>'special_update'),
					array('name'=>'删除专题','auth_tag'=>'special_delete'),
                ),
				'hide'=>1,
            ),
			array(
                'title'=>'内链关键词',
                'url'=>'/index.php/admin/nlink/index/',
                'auth_tag'=>'nlink',
                'auth_func'=>array(
                    array('name'=>'查看内链关键词','auth_tag'=>'nlink_index'),
                    array('name'=>'编辑内链关键词','auth_tag'=>'nlink_update'),
                    array('name'=>'删除u内链关键词','auth_tag'=>'nlink_delete'),
                ),
				'hide'=>1,
            ),
			array(
                'title'=>'标签管理',
                'url'=>'/index.php/admin/tag/index/',
                'auth_tag'=>'tag',
                'auth_func'=>array(
                    array('name'=>'查看标签','auth_tag'=>'tag_index'),
                    array('name'=>'编辑标签','auth_tag'=>'tag_update'),
					array('name'=>'删除标签','auth_tag'=>'tag_delete'),
                ),
				'hide'=>1,
            ),
			
			array(
                'title'=>'推荐位管理',
                'url'=>'/index.php/admin/recommend/index/',
                'auth_tag'=>'recommend',
                'auth_func'=>array(
                    array('name'=>'查看推荐位','auth_tag'=>'recommend_index'),
                    array('name'=>'编辑推荐位','auth_tag'=>'recommend_update'),
					array('name'=>'删除推荐位','auth_tag'=>'recommend_delete'),
                ),
				'hide'=>1,
            ),
			
         ),
    ),
	
	
	
	array('title'=>'模块管理','url'=>'/index.php/admin/frame/left/?auth_tag=module','auth_tag'=>'module',
        'smenu'=>array(
		    
			array(
                'title'=>'广告管理',
                'url'=>'/index.php/admin/adArea',
                'auth_tag'=>'ad_area',
                'auth_func'=>array(
                    array('name'=>'查看广告位','auth_tag'=>'ad_area_show'),
                    array('name'=>'新增广告位','auth_tag'=>'ad_area_add'),
                    array('name'=>'修改广告位','auth_tag'=>'ad_area_edit'),
					array('name'=>'删除广告位','auth_tag'=>'ad_area_del'),
                ),
            ),
			array(
                'title'=>'友情链接',
                'url'=>'/index.php/admin/flink/index/',
                'auth_tag'=>'flink',
                'auth_func'=>array(
                    array('name'=>'查看友情链接','auth_tag'=>'flink_show'),
                    array('name'=>'新增友情链接','auth_tag'=>'flink_add'),
                    array('name'=>'修改友情链接','auth_tag'=>'flink_edit'),
					array('name'=>'删除友情链接','auth_tag'=>'flink_del'),
                ),
            ),
            array(
            		'title'=>'seo页面',
            		'url'=>'/index.php/admin/siteSeo/index/',
            		'auth_tag'=>'siteSeo',
            		'auth_func'=>array(
            				array('name'=>'查看seo页面','auth_tag'=>'siteSeo_show'),
            				array('name'=>'新增seo页面','auth_tag'=>'siteSeo_add'),
            				array('name'=>'修改seo页面','auth_tag'=>'siteSeo_edit'),
            				array('name'=>'删除seo页面','auth_tag'=>'siteSeo_del'),
            		),
            ),
			array(
                'title'=>'投票管理',
                'url'=>'/index.php/admin/vote/index/',
                'auth_tag'=>'vote',
                'auth_func'=>array(
                    array('name'=>'查看投票','auth_tag'=>'vote_show'),
					array('name'=>'查看结果统计','auth_tag'=>'vote_result_show'),
                    array('name'=>'新增投票','auth_tag'=>'vote_add'),
                    array('name'=>'修改投票','auth_tag'=>'vote_edit'),
					array('name'=>'删除投票','auth_tag'=>'vote_del'),
                ),
				'hide'=>1,
            ),
			array(
                'title'=>'伪静态管理',
                'url'=>'/index.php/admin/rewrite/index/',
                'auth_tag'=>'rewrite',
                'auth_func'=>array(
                    array('name'=>'查看伪静态','auth_tag'=>'rewrite_show'),
                    array('name'=>'新增伪静态','auth_tag'=>'rewrite_add'),
                    array('name'=>'修改伪静态','auth_tag'=>'rewrite_edit'),
					array('name'=>'删除伪静态','auth_tag'=>'rewrite_del'),
                ),
            ),
			array(
                'title'=>'资源管理',
                'url'=>'/index.php/admin/attachment/index/',
                'auth_tag'=>'attachment',
                'auth_func'=>array(
                    array('name'=>'查看资源','auth_tag'=>'attachment_show'),
					array('name'=>'删除资源','auth_tag'=>'attachment_del'),
                ),
            ),	
         ),
    ),
    array('title'=>'模版管理','url'=>'/index.php?m=admin&c=left?auth_tag=templates','auth_tag'=>'templates','hide'=>1,
        'smenu'=>array(
            array(
                'title'=>'主题风格',
                'url'=>'/index.php/admin/style/index/',
                'auth_tag'=>'style',
                'auth_func'=>array(
                    array('name'=>'查看风格','auth_tag'=>'style_show'),
                    array('name'=>'新增风格','auth_tag'=>'style_add'),
                    array('name'=>'修改风格','auth_tag'=>'style_edit'),
					array('name'=>'删除风格','auth_tag'=>'style_del'),
                ),
            ),
			array(
                'title'=>'模版编辑',
                'url'=>'/index.php/admin/templates',
                'auth_tag'=>'templates',
                'auth_func'=>array(
                    array('name'=>'查看模版','auth_tag'=>'templates_show'),
                    array('name'=>'新增模版','auth_tag'=>'templates_add'),
                    array('name'=>'修改模版','auth_tag'=>'templates_edit'),
					array('name'=>'删除模版','auth_tag'=>'templates_del'),
                ),
            ),
         ),
    ),
    array(
        'title'=>'用户中心',
        'url'=>'/index.php/admin/left/index?auth_tag=member',
        'auth_tag'=>'member',
		'hide'=>0,
        'smenu'=>array(
		    array(
                 'title'=>'会员组管理',
                 'url'=>'/index.php/admin/userGroup/index/','hide'=>1,
                 'auth_tag'=>'A501',
                 'auth_func'=>array(
					array('name'=>'显示用户列表','auth_tag'=>'A50100'),
                    array('name'=>'启用停用账号','auth_tag'=>'A50101'),
                    array('name'=>'添加用户','auth_tag'=>'A50102'),
                    array('name'=>'修改用户资料','auth_tag'=>'A50103'),
					array('name'=>'删除账号','auth_tag'=>'A50101'),
                    array('name'=>'读取用户资料','auth_tag'=>'A50104'),
                ),
			),
			
             array(
                 'title'=>'会员管理',
                 'url'=>'/index.php/admin/user/index/',
                 'auth_tag'=>'user',
                 'auth_func'=>array(
					array('name'=>'显示用户列表','auth_tag'=>'user_index'),
                    array('name'=>'启用停用账号','auth_tag'=>'user_changestate'),
                    array('name'=>'添加用户','auth_tag'=>'user_add'),
                    array('name'=>'修改用户资料','auth_tag'=>'user_edit'),
					array('name'=>'删除账号','auth_tag'=>'user_del'),
                    array('name'=>'读取用户资料','auth_tag'=>'user_detail'),
                ),
			),
			 array(
                 'title'=>'积分管理',
                 'url'=>'/index.php/admin/userPoints/index/',
                 'auth_tag'=>'user_points',
                 'auth_func'=>array(
					array('name'=>'添加积分','auth_tag'=>'A50100'),
                    array('name'=>'修改积分','auth_tag'=>'A50101'),
                    array('name'=>'删除积分','auth_tag'=>'A50102'),
                ),
			 		'hide'=>1,
			),
             array(
                 'title'=>'用户登录记录',
                 'url'=>'/index.php/admin/userLogin/index/',
                 'auth_tag'=>'A502',
                 'auth_func'=>array(
					array('name'=>'显示用户列表','auth_tag'=>'A50200'),
                ),
			),
             array(
                 'title'=>'站内信',
                 'url'=>'/index.php/admin/pmList/index/',
                 'auth_tag'=>'pm',
                 'auth_func'=>array(
					array('name'=>'显示站内信列表','auth_tag'=>'pm_show'),
                    array('name'=>'显示隐藏站类信','auth_tag'=>'pm_display'),
                    array('name'=>'修改站内信','auth_tag'=>'pm_edit'),
                    array('name'=>'添加站内信','auth_tag'=>'pm_add'),
                    array('name'=>'读取站内信','auth_tag'=>'pm_read'),
                ),
                'hide'=>1,
             ),
			 array(
                 'title'=>'订单管理',
                 'url'=>'/index.php/admin/userOrder/',
                 'auth_tag'=>'user_order',
                 'auth_func'=>array(
					array('name'=>'显示订单列表','auth_tag'=>'user_order_show'),
                    array('name'=>'修改订单','auth_tag'=>'user_order_edit'),
                    array('name'=>'添加订单','auth_tag'=>'user_order_add'),
                    array('name'=>'删除订单','auth_tag'=>'user_order_read'),
                ),
                'hide'=>0,
             ),
			 array(
                 'title'=>'兑换管理',
                 'url'=>'/index.php?m=admin&c=exchange_code',
                 'auth_tag'=>'exchange_code',
                 'auth_func'=>array(
					array('name'=>'显示兑换列表','auth_tag'=>'exchange_code_show'),
                    array('name'=>'修改兑换','auth_tag'=>'exchange_code_edit'),
                    array('name'=>'添加兑换','auth_tag'=>'exchange_code_add'),
                    array('name'=>'删除兑换','auth_tag'=>'exchange_code_read'),
                ),
                'hide'=>1,
             ),
			 
			 array(
                 'title'=>'充值管理',
                 'url'=>'/index.php/admin/userPay/index',
                 'auth_tag'=>'user_pay',
                 'auth_func'=>array(
					array('name'=>'显示充值列表','auth_tag'=>'user_pay_show'),
                    array('name'=>'修改充值','auth_tag'=>'user_pay_edit'),
                    array('name'=>'添加充值','auth_tag'=>'user_pay_add'),
                    array('name'=>'读取充值','auth_tag'=>'user_pay_read'),
                ),
                'hide'=>0,
             ),
			 
			 array(
                 'title'=>'配送方式管理',
                 'url'=>'/index.php?m=admin&c=shipping',
                 'auth_tag'=>'shipping',
                 'auth_func'=>array(
					array('name'=>'显示配送方式','auth_tag'=>'shipping_show'),
                    array('name'=>'修改配送方式','auth_tag'=>'shipping_edit'),
                    array('name'=>'添加配送方式','auth_tag'=>'shipping_add'),
                    array('name'=>'删除配送方式','auth_tag'=>'shipping_read'),
                ),
                'hide'=>1,
             ),
			 array(
                 'title'=>'优惠券管理',
                 'url'=>'/index.php?m=admin&c=coupons',
                 'auth_tag'=>'coupons',
                 'auth_func'=>array(
					array('name'=>'优惠券列表','auth_tag'=>'coupons_show'),
                    array('name'=>'修改优惠券','auth_tag'=>'coupons_edit'),
                    array('name'=>'添加优惠券','auth_tag'=>'coupons_add'),
                    array('name'=>'删除优惠券','auth_tag'=>'coupons_del'),
                ),
				'hide'=>1,
             ),
			 array(
                 'title'=>'优惠活动管理',
                 'url'=>'/index.php?m=admin&c=activity',
                 'auth_tag'=>'activity',
                 'auth_func'=>array(
					array('name'=>'优惠活动列表','auth_tag'=>'activity_show'),
                    array('name'=>'修改优惠活动','auth_tag'=>'activity_edit'),
                    array('name'=>'优惠活动优惠券','auth_tag'=>'activity_add'),
                    array('name'=>'优惠活动优惠券','auth_tag'=>'activity_del'),
                ),
				'hide'=>1,
             ),
			 array(
                 'title'=>'团购活动管理',
                 'url'=>'/index.php?m=admin&c=group_goods',
                 'auth_tag'=>'activity',
                 'auth_func'=>array(
					array('name'=>'团购活动列表','auth_tag'=>'group_goods_show'),
                    array('name'=>'修改团购活动','auth_tag'=>'group_goods_edit'),
                    array('name'=>'优惠团购活动','auth_tag'=>'group_goods_add'),
                    array('name'=>'优惠团购活动','auth_tag'=>'group_goods_del'),
                ),
				'hide'=>1,
             ),
         ),
    ),
    		array(
    				'title'=>'服务点管理',
    				'url'=>'/index.php/admin/left/index?auth_tag=company',
    				'auth_tag'=>'company',
    				'hide'=>0,
    				'smenu'=>array(
    						array(
    								'title'=>'服务点管理',
    								'url'=>'/index.php/admin/companyUser/index/',
    								'auth_tag'=>'ad_area',
    								'auth_func'=>array(
    										array('name'=>'查看服务点','auth_tag'=>'ad_area_show'),
    										array('name'=>'新增服务点','auth_tag'=>'ad_area_add'),
    										array('name'=>'修改服务点','auth_tag'=>'ad_area_edit'),
    										array('name'=>'删除服务点','auth_tag'=>'ad_area_del'),
    								),
    								'hide'=>0,
    						),	
    						array(
    								'title'=>'站内信',
    								'url'=>'/index.php/admin/pmList/index/',
    								'auth_tag'=>'pm',
    								'auth_func'=>array(
    										array('name'=>'显示站内信列表','auth_tag'=>'pm_show'),
    										array('name'=>'显示隐藏站类信','auth_tag'=>'pm_display'),
    										array('name'=>'修改站内信','auth_tag'=>'pm_edit'),
    										array('name'=>'添加站内信','auth_tag'=>'pm_add'),
    										array('name'=>'读取站内信','auth_tag'=>'pm_read'),
    								),
    								'hide'=>0,
    						),
    		
    						
    				),
    		),
	array('title'=>'系统功能','url'=>'/index.php?m=admin&c=left?auth_tag=A100','auth_tag'=>'setting',
        'smenu'=>array(
	        array(
	        		'title'=>'系统参数',
	        		'url'=>'/index.php/admin/setting/index/',
	        		'auth_tag'=>'setting',
	        		'auth_func'=>array(
	        		),
	        ),
			array(
                'title'=>'模型管理',
                'url'=>'/index.php/admin/infoModel/index/',
                'auth_tag'=>'infoModel',
                'auth_func'=>array(
                    array('name'=>'查看模型','auth_tag'=>'infoModel_show'),
                    array('name'=>'新增模型','auth_tag'=>'infoModel_add'),
                    array('name'=>'修改模型','auth_tag'=>'infoModel_edit'),
					array('name'=>'删除模型','auth_tag'=>'infoModel_del'),
                ),
            ),
			
			array(
			        'title'=>'管理员分组',
			        'url'=>'/index.php/admin/adminGroup/index/',
			        'auth_tag'=>'admin_group',
			        'auth_func'=>array(
			                array('name'=>'查看模型','auth_tag'=>'admin_group_show'),
			                array('name'=>'新增模型','auth_tag'=>'admin_group_add'),
			                array('name'=>'修改模型','auth_tag'=>'admin_group_edit'),
			                array('name'=>'删除模型','auth_tag'=>'admin_group_del'),
			        ),
			),
			array(
			        'title'=>'管理员角色',
			        'url'=>'/index.php/admin/adminRole/index/',
			        'auth_tag'=>'admin_group',
			        'auth_func'=>array(
			                array('name'=>'查看角色','auth_tag'=>'admin_role_show'),
			                array('name'=>'新增角色','auth_tag'=>'admin_role_add'),
			                array('name'=>'修改角色','auth_tag'=>'admin_role_edit'),
			                array('name'=>'删除角色','auth_tag'=>'admin_role_del'),
			        ),
			),
			array(
			        'title'=>'系统管理员',
			        'url'=>'/index.php/admin/adminUser/index/',
			        'auth_tag'=>'adminUser',
			        'auth_func'=>array(
			                array('name'=>'查看管理员','auth_tag'=>'adminUser_show'),
			                array('name'=>'新增管理员','auth_tag'=>'adminUser_add'),
			                array('name'=>'修改管理员','auth_tag'=>'adminUser_edit'),
			                array('name'=>'删除管理员','auth_tag'=>'adminUser_del'),
			        ),
			),
			array(
			        'title'=>'管理员日志',
			        'url'=>'/index.php/admin/adminAclog/index',
			        'auth_tag'=>'logs',
			        'auth_func'=>array(
			            array('name'=>'查看管理员日志','auth_tag'=>'logs_show'),
			        ),
			),
			array(
                'title'=>'清空缓存',
                'url'=>'/index.php/admin/clearCache/index',
                'auth_tag'=>'clear_cache',
                'auth_func'=>array(
                    array('name'=>'清空缓存','auth_tag'=>'clear_cache'),
                ),
				'hide'=>0,
            ),
			array(
                'title'=>'备份管理',
                'url'=>'/ebak/admin.php',
                'auth_tag'=>'bak',
                'auth_func'=>array(
                    
                ),
                
            ),
         ),
    ),
	array('title'=>'表单管理','url'=>'/index.php?m=admin&c=left?auth_tag=form','auth_tag'=>'form',
        'smenu'=>array(
         ),
    ),	
    
);

        
}
?>